#!/usr/bin/env node

const { version, repository } = require('../package.json');
const { exec } = require('child_process');

console.log('Releasing new version...');

let published = false;

exec('git push --tags', (error) => {
    if (error) {
        console.error(`⛔ Couldn't push tags to ${repository}! \n ${error}`);
        return;
    }

    console.log(`✅ Successfully pushed tags to ${repository}`);
});

exec('yarn publish', (error) => {
    if (error) {
        console.error(`⛔ Couldn't publish package to npm registry! \n ${error}`);
        return;
    }

    published = true;

    console.log('✅ Successfully published new version on npm!');
});

exec('git push', (error) => {
    if (error) {
        console.error(`⛔ Couldn't push changes to ${repository}! \n ${error}`);
        return;
    }

    console.log(`✅ Successfully pushed changes to ${repository}`);
});

if (published) {
    console.log(`✅ Successfully released version ${version} on npm!`);
}
