#!/usr/bin/env node

const { version, repository } = require('../package.json');
const { exec } = require('child_process');

// git push --tags && yarn publish . && git push && echo \"Successfully released version $npm_package_version!\"
// exec(`git push --tags && yarn publish . && git push && echo 'Successfully released version ${version}!'`);

console.log('Releasing new version...');

let published = false;

exec('git push --tags', (error) => {
    if (error) {
        console.error(`⛔ Couldn't push tags to ${repository}!`);
        return;
    }

    console.log(`✅ Successfully pushed tags to ${repository}`);
});
exec('yarn publish', (error) => {
    if (error) {
        console.error('⛔ Couldn\'t publish package to npm registry!');
        return;
    }

    published = true;

    console.log('✅ Successfully published new version on npm!');
});
exec('git push', (error) => {
    if (error) {
        console.error(`⛔ Couldn\'t push changes to ${repository}`);
    }

    console.log(`✅ Successfully pushed changes to ${repository}`);
});

if (published) {
    console.log(`✅ Successfully released version ${version} on npm!`);
}
