name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
      # You may pin to the exact commit or the version.
      # uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba
        uses: denoland/setup-deno@v1.1.4
        # with:
          # The Deno version to install. Can be a semver version of a stable release, "canary" for the latest canary, or the Git hash of a specific canary release.
          # deno-version: # optional, default is 1.x
          

      - name: Publish package
        run: deno publish
